In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

import joblib

In [2]:
df = pd.read_csv("student_dropout_dataset_v3.csv")

df.head()

,Student_ID,Age,Gender,Family_Income,Internet_Access,Study_Hours_per_Day,Attendance_Rate,Assignment_Delay_Days,Travel_Time_Minutes,Part_Time_Job,Scholarship,Stress_Index,GPA,Semester_GPA,CGPA,Semester,Department,Parental_Education,Dropout
0,1,22.1,Male,25000.0,Yes,3.36,86.1,2,20.4,Yes,No,5.5,0.96,0.90,0.90,Year 1,Arts,High School,0
1,2,20.7,Male,25000.0,Yes,4.30,68.0,2,44.0,No,No,6.8,1.28,1.20,1.19,Year 3,Engineering,Bachelor,1
2,3,22.4,Male,40183.0,Yes,4.40,70.9,0,48.9,Yes,No,5.5,1.68,1.32,1.32,Year 1,Arts,Master,0
3,4,24.4,Male,NaN,Yes,NaN,82.2,2,38.6,No,No,NaN,1.78,1.77,1.77,Year 1,CS,High School,1
4,5,20.5,Female,25319.0,Yes,4.19,75.7,1,23.0,No,No,7.0,1.48,0.91,0.87,Year 4,Business,Bachelor,0

In [3]:
print(df.shape)

print(df.info())

print(df.isnull().sum())

df.head()

(10000, 19)
<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Student_ID             10000 non-null  int64
 1   Age                    10000 non-null  float64
 2   Gender                 10000 non-null  str
 3   Family_Income          9500 non-null   float64
 4   Internet_Access        10000 non-null  str
 5   Study_Hours_per_Day    9500 non-null   float64
 6   Attendance_Rate        10000 non-null  float64
 7   Assignment_Delay_Days  10000 non-null  int64
 8   Travel_Time_Minutes    10000 non-null  float64
 9   Part_Time_Job          10000 non-null  str
 10  Scholarship            10000 non-null  str
 11  Stress_Index           9500 non-null   float64
 12  GPA                    10000 non-null  float64
 13  Semester_GPA           10000 non-null  float64
 14  CGPA                   10000 non-null  float64
 15  Semester               10000 non-null  str
 16  Department             10000 non-null  str
 17  Parental_Education     9489 non-null   str
 18  Dropout                10000 non-null  int64
dtypes: float64(9), int64(3), str(7)
memory usage: 1.8 MB
None
Student_ID                 0
Age                        0
Gender                     0
Family_Income            500
Internet_Access            0
Study_Hours_per_Day      500
Attendance_Rate            0
Assignment_Delay_Days      0
Travel_Time_Minutes        0
Part_Time_Job              0
Scholarship                0
Stress_Index             500
GPA                        0
Semester_GPA               0
CGPA                       0
Semester                   0
Department                 0
Parental_Education       511
Dropout                    0
dtype: int64

,Student_ID,Age,Gender,Family_Income,Internet_Access,Study_Hours_per_Day,Attendance_Rate,Assignment_Delay_Days,Travel_Time_Minutes,Part_Time_Job,Scholarship,Stress_Index,GPA,Semester_GPA,CGPA,Semester,Department,Parental_Education,Dropout
0,1,22.1,Male,25000.0,Yes,3.36,86.1,2,20.4,Yes,No,5.5,0.96,0.90,0.90,Year 1,Arts,High School,0
1,2,20.7,Male,25000.0,Yes,4.30,68.0,2,44.0,No,No,6.8,1.28,1.20,1.19,Year 3,Engineering,Bachelor,1
2,3,22.4,Male,40183.0,Yes,4.40,70.9,0,48.9,Yes,No,5.5,1.68,1.32,1.32,Year 1,Arts,Master,0
3,4,24.4,Male,NaN,Yes,NaN,82.2,2,38.6,No,No,NaN,1.78,1.77,1.77,Year 1,CS,High School,1
4,5,20.5,Female,25319.0,Yes,4.19,75.7,1,23.0,No,No,7.0,1.48,0.91,0.87,Year 4,Business,Bachelor,0

In [4]:
encoder = LabelEncoder()

for col in df.columns:
    if df[col].dtype == "object":
        df[col] = encoder.fit_transform(df[col])

df.head()

,Student_ID,Age,Gender,Family_Income,Internet_Access,Study_Hours_per_Day,Attendance_Rate,Assignment_Delay_Days,Travel_Time_Minutes,Part_Time_Job,Scholarship,Stress_Index,GPA,Semester_GPA,CGPA,Semester,Department,Parental_Education,Dropout
0,1,22.1,Male,25000.0,Yes,3.36,86.1,2,20.4,Yes,No,5.5,0.96,0.90,0.90,Year 1,Arts,High School,0
1,2,20.7,Male,25000.0,Yes,4.30,68.0,2,44.0,No,No,6.8,1.28,1.20,1.19,Year 3,Engineering,Bachelor,1
2,3,22.4,Male,40183.0,Yes,4.40,70.9,0,48.9,Yes,No,5.5,1.68,1.32,1.32,Year 1,Arts,Master,0
3,4,24.4,Male,NaN,Yes,NaN,82.2,2,38.6,No,No,NaN,1.78,1.77,1.77,Year 1,CS,High School,1
4,5,20.5,Female,25319.0,Yes,4.19,75.7,1,23.0,No,No,7.0,1.48,0.91,0.87,Year 4,Business,Bachelor,0

In [11]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

categorical_cols = [
    'Gender',
    'Internet_Access',
    'Part_Time_Job',
    'Scholarship',
    'Semester',
    'Department',
    'Parental_Education'
]

for col in categorical_cols:
    df[col] = le.fit_transform(df[col])

print(df.dtypes)

Student_ID                 int64
Age                      float64
Gender                     int64
Family_Income            float64
Internet_Access            int64
Study_Hours_per_Day      float64
Attendance_Rate          float64
Assignment_Delay_Days      int64
Travel_Time_Minutes      float64
Part_Time_Job              int64
Scholarship                int64
Stress_Index             float64
GPA                      float64
Semester_GPA             float64
CGPA                     float64
Semester                   int64
Department                 int64
Parental_Education         int64
Dropout                    int64
dtype: object

In [12]:
X = df.drop("Dropout", axis=1)
y = df["Dropout"]

In [32]:
print(X.columns)

Index(['Student_ID', 'Age', 'Gender', 'Family_Income', 'Internet_Access',
       'Study_Hours_per_Day', 'Attendance_Rate', 'Assignment_Delay_Days',
       'Travel_Time_Minutes', 'Part_Time_Job', 'Scholarship', 'Stress_Index',
       'GPA', 'Semester_GPA', 'CGPA', 'Semester', 'Department',
       'Parental_Education'],
      dtype='str')

In [33]:
print(df["Gender"].unique())
print(df["Internet_Access"].unique())
print(df["Part_Time_Job"].unique())
print(df["Scholarship"].unique())
print(df["Semester"].unique())
print(df["Department"].unique())
print(df["Parental_Education"].unique())

[1 0]
[1 0]
[1 0]
[0 1]
[0 2 3 1]
[0 3 2 1 4]
[1 0 2 4 3]

In [34]:
df.head()

,Student_ID,Age,Gender,Family_Income,Internet_Access,Study_Hours_per_Day,Attendance_Rate,Assignment_Delay_Days,Travel_Time_Minutes,Part_Time_Job,Scholarship,Stress_Index,GPA,Semester_GPA,CGPA,Semester,Department,Parental_Education,Dropout
0,1,22.1,1,25000.0,1,3.36,86.1,2,20.4,1,0,5.5,0.96,0.90,0.90,0,0,1,0
1,2,20.7,1,25000.0,1,4.30,68.0,2,44.0,0,0,6.8,1.28,1.20,1.19,2,3,0,1
2,3,22.4,1,40183.0,1,4.40,70.9,0,48.9,1,0,5.5,1.68,1.32,1.32,0,0,2,0
3,4,24.4,1,NaN,1,NaN,82.2,2,38.6,0,0,NaN,1.78,1.77,1.77,0,2,1,1
4,5,20.5,0,25319.0,1,4.19,75.7,1,23.0,0,0,7.0,1.48,0.91,0.87,3,1,0,0

In [13]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

In [17]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [18]:
lr = LogisticRegression(max_iter=5000)

lr.fit(X_train, y_train)

LogisticRegression(max_iter=5000)

In [20]:
print(X_train.shape)
print(X_test.shape)

print(type(X_train))
print(type(X_test))

(8000, 18)
(2000, 18)
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

In [22]:
print(X_test[:5])

[[ 4.29612631e-01  2.69375186e+00  1.00075028e+00             nan
   3.73849567e-01             nan -2.31047581e+00 -5.92598480e-01
   1.56638976e-01  1.22156123e+00 -7.34605936e-01             nan
   1.60652573e+00  1.59821891e+00  1.55532362e+00  1.32954128e+00
  -1.14070277e-03 -9.44689987e-01]
 [-1.13423515e-01 -1.09219231e+00 -9.99250281e-01             nan
   3.73849567e-01             nan -2.87659431e+00 -5.92598480e-01
   3.73862401e-01  1.22156123e+00  1.36127405e+00             nan
   5.40871426e-01  7.67788100e-01  6.85972101e-01  1.32954128e+00
  -7.03111636e-01 -4.95674125e-02]
 [-1.13611850e+00 -3.91091538e-01  1.00075028e+00             nan
   3.73849567e-01             nan -2.19725212e+00 -1.33823985e+00
   3.82217148e-01 -8.18624540e-01 -7.34605936e-01             nan
  -6.37949704e-01 -7.53113268e-01 -7.72294968e-01  4.34227286e-01
  -1.14070277e-03 -9.44689987e-01]
 [-9.33367185e-02 -1.71711264e-02  1.00075028e+00             nan
   3.73849567e-01             nan -3.21626540e+00  8.98684263e-01
  -3.86419586e-01 -8.18624540e-01 -7.34605936e-01             nan
  -1.60929831e+00 -1.24763948e+00 -1.21164466e+00 -4.61086705e-01
  -1.14070277e-03 -9.44689987e-01]
 [-1.69874339e-01  1.10459011e+00  1.00075028e+00             nan
   3.73849567e-01             nan -3.06530047e+00  8.98684263e-01
   3.15379172e-01  1.22156123e+00  1.36127405e+00             nan
   1.16495819e-01  4.50544870e-01  5.17710516e-01  1.32954128e+00
  -7.03111636e-01  2.63580031e+00]]

In [24]:
import numpy as np

print("NaN in X_train:", np.isnan(X_train).sum())
print("NaN in X_test:", np.isnan(X_test).sum())

NaN in X_train: 0
NaN in X_test: 1500

In [25]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='mean')

X_train = imputer.fit_transform(X_train)
X_test = imputer.transform(X_test)

In [26]:
lr = LogisticRegression(max_iter=5000)

lr.fit(X_train, y_train)

pred_lr = lr.predict(X_test)

from sklearn.metrics import accuracy_score

print("Accuracy:", accuracy_score(y_test, pred_lr))

Accuracy: 0.8095

In [27]:
print(np.isnan(X_train).sum())
print(np.isnan(X_test).sum())

0
0

In [28]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)

rf = RandomForestClassifier()
rf.fit(X_train, y_train)

print("Decision Tree:", dt.score(X_test, y_test))
print("Random Forest:", rf.score(X_test, y_test))

Decision Tree: 0.7475
Random Forest: 0.806

In [29]:
from sklearn.ensemble import GradientBoostingClassifier

gb = GradientBoostingClassifier()
gb.fit(X_train, y_train)

print("Gradient Boosting:", gb.score(X_test, y_test))

Gradient Boosting: 0.8065

In [35]:
import joblib

joblib.dump(lr, "best_model.pkl")
print("Model saved successfully!")

Model saved successfully!

In [36]:
import os
print(os.listdir())

['App.py', 'best_model.pkl', 'project.ipynb', 'scaler.pkl', 'student_dropout_dataset_v3.csv']

In [37]:
print(df["Department"].value_counts())
print(df["Parental_Education"].value_counts())
print(df["Semester"].value_counts())

Department
4    2061
0    2026
1    2002
2    1974
3    1937
Name: count, dtype: int64
Parental_Education
0    3949
1    3072
2    2003
4     511
3     465
Name: count, dtype: int64
Semester
3    2536
2    2521
1    2488
0    2455
Name: count, dtype: int64

In [38]:
print(X.columns.tolist())

['Student_ID', 'Age', 'Gender', 'Family_Income', 'Internet_Access', 'Study_Hours_per_Day', 'Attendance_Rate', 'Assignment_Delay_Days', 'Travel_Time_Minutes', 'Part_Time_Job', 'Scholarship', 'Stress_Index', 'GPA', 'Semester_GPA', 'CGPA', 'Semester', 'Department', 'Parental_Education']

In [40]:
df.head(10)

,Student_ID,Age,Gender,Family_Income,Internet_Access,Study_Hours_per_Day,Attendance_Rate,Assignment_Delay_Days,Travel_Time_Minutes,Part_Time_Job,Scholarship,Stress_Index,GPA,Semester_GPA,CGPA,Semester,Department,Parental_Education,Dropout
0,1,22.1,1,25000.0,1,3.36,86.1,2,20.4,1,0,5.5,0.96,0.90,0.90,0,0,1,0
1,2,20.7,1,25000.0,1,4.30,68.0,2,44.0,0,0,6.8,1.28,1.20,1.19,2,3,0,1
2,3,22.4,1,40183.0,1,4.40,70.9,0,48.9,1,0,5.5,1.68,1.32,1.32,0,0,2,0
3,4,24.4,1,NaN,1,NaN,82.2,2,38.6,0,0,NaN,1.78,1.77,1.77,0,2,1,1
4,5,20.5,0,25319.0,1,4.19,75.7,1,23.0,0,0,7.0,1.48,0.91,0.87,3,1,0,0
5,6,20.5,1,25000.0,1,4.11,89.1,2,47.1,0,1,6.0,2.52,2.72,2.69,2,1,4,0
6,7,24.5,1,25000.0,1,3.00,78.2,1,37.4,1,1,7.3,0.64,0.33,0.44,3,2,0,0
7,8,22.7,0,25000.0,1,2.12,86.4,1,34.0,0,1,6.5,1.79,1.14,1.14,0,0,1,0
8,9,20.0,1,57413.0,1,4.07,97.5,3,52.1,0,0,4.2,3.08,2.81,2.81,0,2,1,0
9,10,22.2,0,44930.0,1,2.98,82.2,1,19.7,0,0,6.7,1.59,1.73,1.73,0,4,2,0

In [39]:
type(lr)

sklearn.linear_model._logistic.LogisticRegression

In [31]:
joblib.dump(scaler, "scaler.pkl")
print("Scaler saved successfully!")

Scaler saved successfully!